services:
  db:
    image: mysql:8.2.0
    container_name: notiocli-MYSQL-container
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB_NAME}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "${MYSQL_DB_PORT}:${MYSQL_DB_PORT}"
volumes:
  db_data: